### ISSUE TITLE
Rails 3.2: db:migrate does not working

### ISSUE THREAD

**Issue by dmitry-a-l** [karledurante/secondbase#7]
When I run rake db:migrate I have

```
undefined method `schema_cache' for ActiveRecord::Base:Class
.bundle/ruby/1.9.1/gems/activerecord-3.2.1/lib/active_record/dynamic_matchers.rb:50:in `method_missing'
.bundle/ruby/1.9.1/gems/arel-3.0.0/lib/arel/visitors/to_sql.rb:11:in `initialize'
.bundle/ruby/1.9.1/gems/secondbase-0.5.0/lib/secondbase.rb:31:in `new'
.bundle/ruby/1.9.1/gems/secondbase-0.5.0/lib/secondbase.rb:31:in `reset_visitor_cache'
.bundle/ruby/1.9.1/gems/secondbase-0.5.0/lib/secondbase.rb:15:in `has_runner'
.bundle/ruby/1.9.1/gems/secondbase-0.5.0/lib/secondbase/tasks.rb:92:in `block (3 levels) in <top (required)>'
.....
```

**Comment by karledurante** [comment]
closing since this the same as issue 8.
