### ISSUE TITLE
Apparently Rails 3.2 recursively looks into db/migrate folder

### ISSUE THREAD

**Issue by dmitry-a-l** [karledurante/secondbase#8]
so it wants to make SecondDB migrations in main DB

**Comment by ghost** [comment]
Is this resolved?

**Comment by karledurante** [comment]
Unfortunately, no. The main project I use this on is still Rails 3.0.x, so I haven't had the need to fix this just yet. 

I don't think the fix is hard, just moving where the migrations folder gets created (probably outside of db/migrations). 

Any help would be greatly appreciated!

**Comment by ghost** [comment]
Well i am getting
 rake aborted!
undefined method `schema_cache' for ActiveRecord::Base:Class once I updated to rails 3.2.  Are these related?

**Comment by karledurante** [comment]
That's a good question. I would suspect they are not related. 

I've not tried to use SecondBase with rails 3.2 yet, so I'm honestly unaware of what issues there may be at this time. 

I will be using this in a 3.2 project in the future, so I will address the issues. Just not sure how soon.

**Comment by himanshu-saxena** [comment]
rake aborted!
undefined method `push' for LL("db"):Rake::Scope
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/secondbase-0.5.0/lib/secondbase/rake_method_chain.rb:19:in`override_task'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/secondbase-0.5.0/lib/secondbase/tasks.rb:18:in `block in <top (required)>'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/secondbase-0.5.0/lib/secondbase/tasks.rb:17:in`<top (required)>'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in`block in load'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in`load'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/secondbase-0.5.0/lib/secondbase/railtie.rb:7:in `block in <class:Railtie>'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/railtie.rb:184:in`instance_exec'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/railtie.rb:184:in `block in load_tasks'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/railtie.rb:184:in`each'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/railtie.rb:184:in `load_tasks'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/engine.rb:423:in`block in load_tasks'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/application/railties.rb:8:in `each'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/application/railties.rb:8:in`all'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/engine.rb:423:in `load_tasks'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/application.rb:145:in`load_tasks'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/himanshusaxena/Projects/Mysytes_halosys/Rakefile:8:in`<top (required)>'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/bin/ruby_noexec_wrapper:14:in `eval'
/home/himanshusaxena/.rvm/gems/ruby-1.9.3-p448@mysytes/bin/ruby_noexec_wrapper:14:in`<main>'
(See full trace by running task with --trace)

Getting error on rake db:migrate
